steps:
  - id: "configuration"
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://$_CONFIG_BUCKET/cloud_config.json', 'frontend/cloud_config.json']
  - id: "build"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME', '--target', 'calcus_cloud', '-f', 'Dockerfile', '.']
    timeout: 500s
  - id: "image-storage"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME']
  - id: 'run-migrations'
    name: '${_IMAGE_NAME}'
    entrypoint: 'python'
    args:
      - 'manage.py'
      - 'migrate'
      - '--noinput'
    env:
      - 'DJANGO_SETTINGS_MODULE=calcus.settings'
      - 'POSTGRES_USER=${_POSTGRES_USER}'
      - 'POSTGRES_PORT=${_POSTGRES_PORT}'
      - 'POSTGRES_HOST=${_POSTGRES_HOST}'
      - 'SECRET_KEY=1'
    secretEnv: ['POSTGRES_PASSWORD']
    waitFor: ['image-storage']
  - id: "main-deployment"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'calcus-cloud', '--image', '$_IMAGE_NAME', '--region', 'us-central1', '--update-env-vars=CALCUS_VERSION_HASH=$SHORT_SHA']
  - id: "compute-deployment"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'calcus-cloud-compute', '--image', '$_IMAGE_NAME', '--region', 'us-central1', '--update-env-vars=CALCUS_VERSION_HASH=$SHORT_SHA']

images:
  - $_IMAGE_NAME

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

availableSecrets:
  secretManager:
    - versionName: '${_SECRET_REF}'
      env: 'POSTGRES_PASSWORD'

substitutions:
  _IMAGE_NAME: gcr.io/${_PROJECT_REPO}:latest
