steps:
  - id: "configuration"
    name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'gs://$_CONFIG_BUCKET/cloud_config.json', 'frontend/cloud_config.json']
  - id: "build"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', '$_IMAGE_NAME', '--target', 'calcus_cloud', '-f', 'Dockerfile', '.']
    timeout: 500s
  - id: "image-storage"
    name: 'gcr.io/cloud-builders/docker'
    args: ['push', '$_IMAGE_NAME']
  - id: "main-deployment"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'calcus-cloud', '--image', '$_IMAGE_NAME', '--region', 'us-central1', '--update-env-vars=CALCUS_VERSION_HASH=$SHORT_SHA']
  - id: "compute-deployment"
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: ['run', 'deploy', 'calcus-cloud-compute', '--image', '$_IMAGE_NAME', '--region', 'us-central1', '--update-env-vars=CALCUS_VERSION_HASH=$SHORT_SHA']

images:
  - $_IMAGE_NAME

options:
  dynamic_substitutions: true
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _IMAGE_NAME: gcr.io/${_PROJECT_REPO}:latest
  _DATABASE_PORT: '5432'
