version: "3.4"

services:  
        redis:
                image: redis:latest
                hostname: redis

        web:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_user
                restart: always
                hostname: web
                user: calcus
                command: ./scripts/run_web.sh
                expose:
                        - 8000
                volumes:
                        - ./scr:/calcus/scr
                        - ./results:/calcus/results
                        - ./keys:/calcus/keys
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                        - ./frontend:/calcus/frontend
                links:
                        - redis
                env_file:
                        - ./.env
                depends_on:
                        - postgres
        nginx:
                image: nginx:latest
                ports:
                        - "8080:8080"
                volumes:
                        - ./docker/nginx/:/etc/nginx/conf.d
                        - ./static:/static
                        - .:/calcus
                depends_on: 
                        - web        
        celery_main:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_user
                user: calcus
                command: ./scripts/run_celery_main.sh
                volumes:
                        - ./scr:/calcus/scr
                        - ./results:/calcus/results
                        - ./keys:/calcus/keys
                env_file:
                        - ./.env
                links:
                        - redis
                depends_on:
                        - redis
        celery_comp:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_user
                user: calcus
                command: ./scripts/run_celery_comp.sh
                volumes:
                        - ./scr:/calcus/scr
                        - ./results:/calcus/results
                        - ./keys:/calcus/keys
                env_file:
                        - ./.env
                links:
                        - redis
                depends_on:
                        - redis
        cluster:
                build:
                        context: .
                        dockerfile: Dockerfile
                        target: calcus_user
                user: calcus
                command: ./scripts/run_cluster_daemon.sh
                env_file:
                        - ./.env
                volumes:
                        - ./scr:/calcus/scr
                        - ./results:/calcus/results
                        - ./keys:/calcus/keys
                links:
                        - web
                depends_on:
                        - redis
        postgres:
                image: postgres:11-bullseye
                restart: always
                user: "${UID}:${GID}"
                volumes:
                        - ./data:/var/lib/postgresql/data/:rw
                        - ./backups:/calcus/backups
                        - ./logs:/calcus/logs
                env_file:
                        - ./.env
                environment:
                        - PGDATA=./var/lib/postgresql/data/
                        - POSTGRES_USER=calcus
                        - POSTGRES_DB=calcus


