# Generated by Django 3.2.15 on 2022-10-31 22:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0002_auto_20221025_1953"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowchartorder",
            name="author",
        ),
        migrations.RemoveField(
            model_name="flowchartorder",
            name="ensemble",
        ),
        migrations.RemoveField(
            model_name="flowchartorder",
            name="filter",
        ),
        migrations.RemoveField(
            model_name="flowchartorder",
            name="flowchart",
        ),
        migrations.RemoveField(
            model_name="flowchartorder",
            name="project",
        ),
        migrations.RemoveField(
            model_name="flowchartorder",
            name="structure",
        ),
        migrations.RemoveField(
            model_name="step",
            name="flowchart",
        ),
        migrations.RemoveField(
            model_name="step",
            name="parameters",
        ),
        migrations.RemoveField(
            model_name="step",
            name="parentId",
        ),
        migrations.RemoveField(
            model_name="step",
            name="step",
        ),
        migrations.RemoveField(
            model_name="calculation",
            name="flowchart_order",
        ),
        migrations.RemoveField(
            model_name="calculation",
            name="flowchart_step",
        ),
        migrations.AlterField(
            model_name="calculation",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="frontend.calculationorder",
            ),
        ),
        migrations.DeleteModel(
            name="Flowchart",
        ),
        migrations.DeleteModel(
            name="FlowchartOrder",
        ),
        migrations.DeleteModel(
            name="Step",
        ),
    ]
