# Generated by Django 3.0.3 on 2020-03-05 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20200305_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='type',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
