# Generated by Django 3.0.3 on 2020-03-05 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_calculation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
