# Generated by Django 3.0.3 on 2020-03-05 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_auto_20200305_0116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculation',
            old_name='calculation_name',
            new_name='name',
        ),
    ]
