# Generated by Django 3.0.3 on 2020-03-07 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0005_auto_20200305_0128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='calculations',
        ),
        migrations.AddField(
            model_name='calculation',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Profile'),
        ),
    ]
