# Generated by Django 3.0.3 on 2020-03-07 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_auto_20200307_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculation',
            name='status',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
