# Generated by Django 3.2.16 on 2022-12-04 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0006_auto_20221103_0944"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
    ]
