# Generated by Django 3.2.16 on 2022-12-04 23:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0007_user_is_trial"),
    ]

    operations = [
        migrations.AddField(
            model_name="resourceallocation",
            name="note",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "TRIAL"),
                    (1, "NEW_ACCOUNT"),
                    (2, "TESTER"),
                    (3, "PURCHASE"),
                    (4, "SUBSCRIPTION"),
                    (99, "MANUAL"),
                ],
                default=99,
            ),
        ),
    ]
