# Generated by Django 3.2.16 on 2023-01-17 02:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0011_auto_20230116_2049"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="researchgroup",
            name="PI",
        ),
        migrations.RemoveField(
            model_name="researchgroup",
            name="group_ptr",
        ),
        migrations.RemoveField(
            model_name="user",
            name="in_class",
        ),
        migrations.RemoveField(
            model_name="user",
            name="member_of",
        ),
        migrations.DeleteModel(
            name="ClassGroup",
        ),
        migrations.DeleteModel(
            name="ResearchGroup",
        ),
    ]
