# Generated by Django 3.2.16 on 2023-01-20 21:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0014_auto_20230116_2114"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="random_password",
            field=models.CharField(default="", max_length=64),
        ),
    ]
