# Generated by Django 3.2.16 on 2023-01-26 15:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import hashid_field.field


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0015_user_random_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="last_free_refill",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 1, 1), verbose_name="date"
            ),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    hashid_field.field.BigHashidAutoField(
                        alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                        min_length=13,
                        prefix="",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("duration", models.PositiveSmallIntegerField()),
                ("for_academia", models.BooleanField(default=True)),
                ("start_date", models.DateTimeField(verbose_name="date")),
                ("end_date", models.DateTimeField(verbose_name="date")),
                (
                    "associated_allocation",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="frontend.resourceallocation",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
