# Generated by Django 3.2.16 on 2023-02-09 17:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0017_alter_resourceallocation_note"),
    ]

    operations = [
        migrations.AddField(
            model_name="parameters",
            name="driver",
            field=models.CharField(default="", max_length=100),
        ),
    ]
