# Generated by Django 3.2.18 on 2023-04-26 23:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0018_parameters_driver"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tour_done",
            field=models.BooleanField(default=False),
        ),
    ]
