# Generated by Django 3.2.19 on 2023-05-11 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0019_user_tour_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="stripe_sub_id",
            field=models.CharField(default="", max_length=256),
        ),
    ]
