# Generated by Django 3.2.19 on 2023-05-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0023_user_stripe_will_renew"),
    ]

    operations = [
        migrations.AddField(
            model_name="flowchart",
            name="params",
            field=models.JSONField(null=True),
        ),
    ]
