# Generated by Django 3.2.19 on 2023-05-26 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0024_flowchart_params"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flowchart",
            name="params",
        ),
    ]
