# Generated by Django 3.2.19 on 2023-06-07 01:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0025_remove_flowchart_params"),
    ]

    operations = [
        migrations.AddField(
            model_name="basicstep",
            name="avail_NWChem",
            field=models.BooleanField(default=False),
        ),
    ]
