# Generated by Django 3.2.19 on 2023-06-07 18:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0026_basicstep_avail_nwchem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicstep",
            name="avail_NWChem",
        ),
    ]
