# Generated by Django 3.2.19 on 2023-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0028_basicstep_avail_nwchem"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="esp",
            field=models.TextField(default=""),
        ),
    ]
