# Generated by Django 3.2.19 on 2023-06-26 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0029_property_esp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="basicstep",
            name="avail_NWChem",
        ),
        migrations.RemoveField(
            model_name="property",
            name="esp",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="stripe_sub_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="opted_in_emails",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_cus_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="stripe_will_renew",
        ),
        migrations.RemoveField(
            model_name="user",
            name="tour_done",
        ),
        migrations.AddField(
            model_name="subscription",
            name="duration",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subscription",
            name="for_academia",
            field=models.BooleanField(default=True),
        ),
    ]
