# Generated by Django 3.2.19 on 2023-06-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0030_auto_20230626_1338"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="duration",
        ),
        migrations.RemoveField(
            model_name="subscription",
            name="for_academia",
        ),
        migrations.AddField(
            model_name="basicstep",
            name="avail_NWChem",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="property",
            name="esp",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="subscription",
            name="stripe_sub_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="user",
            name="opted_in_emails",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_cus_id",
            field=models.CharField(default="", max_length=256),
        ),
        migrations.AddField(
            model_name="user",
            name="stripe_will_renew",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="tour_done",
            field=models.BooleanField(default=False),
        ),
    ]
