# Generated by Django 3.2.20 on 2023-07-24 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0034_auto_20230709_1313"),
    ]

    operations = [
        migrations.AlterField(
            model_name="molecule",
            name="inchi",
            field=models.CharField(blank=True, default="", max_length=10000, null=True),
        ),
    ]
