# Generated by Django 3.2.20 on 2023-07-26 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0035_alter_molecule_inchi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="molecule",
            name="inchi",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
