# Generated by Django 3.2.20 on 2023-08-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0036_alter_molecule_inchi"),
    ]

    operations = [
        migrations.AlterField(
            model_name="molecule",
            name="inchi",
            field=models.CharField(blank=True, default="", max_length=10000, null=True),
        ),
    ]
