# Generated by Django 3.2.20 on 2023-09-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0038_batchcalcorder_batchcalculation"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="mo_diagram",
            field=models.TextField(default=""),
        ),
    ]
