# Generated by Django 3.2.18 on 2023-10-01 18:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0039_property_mo_diagram"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="mo_diagram",
            new_name="molden",
        ),
    ]
