# Generated by Django 3.2.18 on 2023-10-01 18:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0040_rename_mo_diagram_property_molden"),
    ]

    operations = [
        migrations.RenameField(
            model_name="property",
            old_name="mo",
            new_name="mo_diagram",
        ),
    ]
