# Generated by Django 3.2.22 on 2023-10-11 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0041_rename_mo_property_mo_diagram"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseProperty",
            fields=[
                (
                    "property_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="frontend.property",
                    ),
                ),
                ("name", models.TextField()),
            ],
            bases=("frontend.property",),
        ),
    ]
