# Generated by Django 3.2.22 on 2023-10-12 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0042_showcaseproperty"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShowcaseEnsemble",
            fields=[
                (
                    "ensemble_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="frontend.ensemble",
                    ),
                ),
                ("label", models.TextField()),
            ],
            bases=("frontend.ensemble",),
        ),
    ]
