# Generated by Django 3.2.22 on 2023-10-12 19:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("frontend", "0043_showcaseensemble"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_free_refill",
            field=models.DateTimeField(
                default=datetime.datetime(2000, 1, 1, 6, 1, tzinfo=utc),
                verbose_name="date",
            ),
        ),
    ]
