# Generated by Django 3.2.25 on 2025-10-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0044_alter_user_last_free_refill"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="constraints",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="current_status",
            field=models.CharField(default="", max_length=1000),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="error_message",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="calculationorder",
            name="constraints",
            field=models.CharField(blank=True, default="", max_length=1000, null=True),
        ),
    ]
