# Generated by Django 3.2.25 on 2025-10-29 17:34

from django.db import migrations, models
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0047_auto_20251029_1216"),
    ]
    """
    migrations.AlterField(
        model_name='calculation',
        name='status',
        field=models.PositiveIntegerField(db_index=True, default=0),
    ),
    """
    operations = [
        migrations.AlterField(
            model_name="calculationorder",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                db_index=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="property",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                db_index=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
        migrations.AlterField(
            model_name="structure",
            name="id",
            field=hashid_field.field.BigHashidAutoField(
                alphabet="abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890",
                db_index=True,
                min_length=13,
                prefix="",
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
