# Generated by Django 3.2.25 on 2025-10-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0048_auto_20251029_1234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="status",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
