# Generated by Django 5.2.11 on 2026-03-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0049_alter_calculation_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationorder",
            name="status",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
