# Generated by CalcUS migration for bucket-backed calculation outputs

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0050_calculationorder_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="output_file_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
