# Generated by Django 5.2.11 on 2026-03-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0050_calculationorder_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calculationorder",
            name="status",
        ),
        migrations.AddField(
            model_name="calculationorder",
            name="calc_statuses",
            field=models.CharField(default="", max_length=50),
        ),
    ]
