# Generated by Django 5.2.11 on 2026-03-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0051_remove_calculationorder_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationorder",
            name="cached_status",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
