# Generated by Django 5.2.11 on 2026-03-02 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0052_calculationorder_cached_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calculationorder",
            old_name="calc_statuses",
            new_name="_calc_statuses",
        ),
    ]
