# Generated by Django 5.2.11 on 2026-03-02 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0053_rename_calc_statuses_calculationorder__calc_statuses"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationorder",
            name="_label",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="calculationorder",
            name="_molecule_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="calculationorder",
            name="_source",
            field=models.CharField(default="", max_length=200),
        ),
    ]
