# Generated by Django 5.2.11 on 2026-03-02 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0054_calculationorder__label_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationorder",
            name="_project_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="calculationorder",
            name="_step_name",
            field=models.CharField(default="", max_length=200),
        ),
    ]
