# Generated by Django 6.0.1 on 2026-03-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0055_calculationorder__project_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculationorder",
            name="total_cpu_time",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
