# Generated by Django 5.2.14 on 2026-05-29 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0051_calculation_output_file_manifest"),
        ("frontend", "0056_calculationorder_total_cpu_time"),
    ]

    operations = []
