# Generated by Django for calculation frame file manifest migration

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0057_merge_20260529_0907"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="frame_file_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
