# Generated by CalcUS migration for bucket-backed Property payloads

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("frontend", "0058_calculation_frame_file_manifest"),
    ]

    operations = [
        migrations.AddField(
            model_name="property",
            name="property_file_manifest",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
